### ISSUE TITLE
How to setup and running examples

### ISSUE THREAD

**Issue by BaseMax** [benedekrozemberczki/pytorch_geometric_temporal#137]
> ModuleNotFoundError: No module named 'torch_geometric_temporal.nn.recurrent'

#### Installing
```
[max@workstation Projects]$ cd pytorch_geometric_temporal/
[max@workstation pytorch_geometric_temporal]$ ls
build  CONTRIBUTING.md  dataset  dist  docs  examples  LICENSE  notebooks  README.md  readthedocs.yml  setup.py  test  torch_geometric_temporal  torch_geometric_temporal.egg-info
[max@workstation pytorch_geometric_temporal]$ sudo python setup.py install
[sudo] password for max: 
running install
running bdist_egg
running egg_info
writing torch_geometric_temporal.egg-info/PKG-INFO
writing dependency_links to torch_geometric_temporal.egg-info/dependency_links.txt
writing requirements to torch_geometric_temporal.egg-info/requires.txt
writing top-level names to torch_geometric_temporal.egg-info/top_level.txt
reading manifest file 'torch_geometric_temporal.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'torch_geometric_temporal.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/torch_geometric_temporal
creating build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn
creating build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/temporalgcn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/dygrae.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/dcrnn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/mpnn_lstm.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/gconv_gru.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/agcrn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/__init__.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/attentiontemporalgcn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/evolvegcno.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/evolvegcnh.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/gconv_lstm.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/gc_lstm.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
copying build/lib/torch_geometric_temporal/nn/recurrent/lrgcn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent
creating build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/mstgcn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/stgcn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/astgcn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/tsagcn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/__init__.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/mtgnn.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/dnntsp.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/attention/gman.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention
copying build/lib/torch_geometric_temporal/nn/__init__.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn
copying build/lib/torch_geometric_temporal/__init__.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal
creating build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/pedalme.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/windmilllarge.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/pems_bay.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/chickenpox.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/windmillmedium.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/mtm.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/__init__.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/metr_la.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/encovid.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/wikimath.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/montevideo_bus.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/twitter_tennis.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
copying build/lib/torch_geometric_temporal/dataset/windmillsmall.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset
creating build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_hetero_graph_temporal_signal.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/train_test_split.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/static_graph_temporal_signal_batch.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_graph_temporal_signal.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_graph_temporal_signal_batch.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/__init__.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_hetero_graph_static_signal_batch.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_graph_static_signal.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/static_graph_temporal_signal.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_hetero_graph_temporal_signal_batch.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_hetero_graph_static_signal.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/static_hetero_graph_temporal_signal_batch.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/dynamic_graph_static_signal_batch.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
copying build/lib/torch_geometric_temporal/signal/static_hetero_graph_temporal_signal.py -> build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/temporalgcn.py to temporalgcn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/dygrae.py to dygrae.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/dcrnn.py to dcrnn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/mpnn_lstm.py to mpnn_lstm.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/gconv_gru.py to gconv_gru.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/agcrn.py to agcrn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/attentiontemporalgcn.py to attentiontemporalgcn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/evolvegcno.py to evolvegcno.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/evolvegcnh.py to evolvegcnh.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/gconv_lstm.py to gconv_lstm.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/gc_lstm.py to gc_lstm.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/recurrent/lrgcn.py to lrgcn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/mstgcn.py to mstgcn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/stgcn.py to stgcn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/astgcn.py to astgcn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/tsagcn.py to tsagcn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/mtgnn.py to mtgnn.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/dnntsp.py to dnntsp.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/attention/gman.py to gman.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/nn/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/pedalme.py to pedalme.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/windmilllarge.py to windmilllarge.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/pems_bay.py to pems_bay.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/chickenpox.py to chickenpox.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/windmillmedium.py to windmillmedium.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/mtm.py to mtm.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/metr_la.py to metr_la.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/encovid.py to encovid.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/wikimath.py to wikimath.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/montevideo_bus.py to montevideo_bus.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/twitter_tennis.py to twitter_tennis.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/dataset/windmillsmall.py to windmillsmall.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_hetero_graph_temporal_signal.py to dynamic_hetero_graph_temporal_signal.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/train_test_split.py to train_test_split.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/static_graph_temporal_signal_batch.py to static_graph_temporal_signal_batch.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_graph_temporal_signal.py to dynamic_graph_temporal_signal.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_graph_temporal_signal_batch.py to dynamic_graph_temporal_signal_batch.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_hetero_graph_static_signal_batch.py to dynamic_hetero_graph_static_signal_batch.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_graph_static_signal.py to dynamic_graph_static_signal.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/static_graph_temporal_signal.py to static_graph_temporal_signal.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_hetero_graph_temporal_signal_batch.py to dynamic_hetero_graph_temporal_signal_batch.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_hetero_graph_static_signal.py to dynamic_hetero_graph_static_signal.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/static_hetero_graph_temporal_signal_batch.py to static_hetero_graph_temporal_signal_batch.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/dynamic_graph_static_signal_batch.py to dynamic_graph_static_signal_batch.cpython-310.pyc
byte-compiling build/bdist.linux-x86_64/egg/torch_geometric_temporal/signal/static_hetero_graph_temporal_signal.py to static_hetero_graph_temporal_signal.cpython-310.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_geometric_temporal.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_geometric_temporal.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_geometric_temporal.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_geometric_temporal.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_geometric_temporal.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/torch_geometric_temporal-0.51.0-py3.10.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_geometric_temporal-0.51.0-py3.10.egg
Removing /usr/lib/python3.10/site-packages/torch_geometric_temporal-0.51.0-py3.10.egg
Copying torch_geometric_temporal-0.51.0-py3.10.egg to /usr/lib/python3.10/site-packages
torch-geometric-temporal 0.51.0 is already the active version in easy-install.pth

Installed /usr/lib/python3.10/site-packages/torch_geometric_temporal-0.51.0-py3.10.egg
Processing dependencies for torch-geometric-temporal==0.51.0
Searching for six==1.16.0
Best match: six 1.16.0
Adding six 1.16.0 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for tqdm==4.62.3
Best match: tqdm 4.62.3
Processing tqdm-4.62.3-py3.10.egg
tqdm 4.62.3 is already the active version in easy-install.pth
Installing tqdm script to /usr/bin

Using /usr/lib/python3.10/site-packages/tqdm-4.62.3-py3.10.egg
Searching for scipy==1.8.0
Best match: scipy 1.8.0
Processing scipy-1.8.0-py3.10-linux-x86_64.egg
scipy 1.8.0 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/scipy-1.8.0-py3.10-linux-x86_64.egg
Searching for numpy==1.21.5
Best match: numpy 1.21.5
Adding numpy 1.21.5 to easy-install.pth file
Installing f2py script to /usr/bin
Installing f2py3 script to /usr/bin
Installing f2py3.10 script to /usr/bin

Using /usr/lib/python3.10/site-packages
Searching for torch-geometric==2.0.3
Best match: torch-geometric 2.0.3
Processing torch_geometric-2.0.3-py3.10.egg
torch-geometric 2.0.3 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/torch_geometric-2.0.3-py3.10.egg
Searching for torch-scatter==2.0.9
Best match: torch-scatter 2.0.9
Processing torch_scatter-2.0.9-py3.10-linux-x86_64.egg
torch-scatter 2.0.9 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/torch_scatter-2.0.9-py3.10-linux-x86_64.egg
Searching for torch-sparse==0.6.12
Best match: torch-sparse 0.6.12
Processing torch_sparse-0.6.12-py3.10-linux-x86_64.egg
torch-sparse 0.6.12 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/torch_sparse-0.6.12-py3.10-linux-x86_64.egg
Searching for pandas==1.3.5
Best match: pandas 1.3.5
Adding pandas 1.3.5 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for Cython==3.0.0a10
Best match: Cython 3.0.0a10
Processing Cython-3.0.0a10-py3.10.egg
Cython 3.0.0a10 is already the active version in easy-install.pth
Installing cygdb script to /usr/bin
Installing cython script to /usr/bin
Installing cythonize script to /usr/bin

Using /usr/lib/python3.10/site-packages/Cython-3.0.0a10-py3.10.egg
Searching for torch==1.10.2
Best match: torch 1.10.2
Adding torch 1.10.2 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /usr/bin
Installing convert-onnx-to-caffe2 script to /usr/bin
Installing torchrun script to /usr/bin

Using /usr/lib/python3.10/site-packages
Searching for decorator==4.4.2
Best match: decorator 4.4.2
Processing decorator-4.4.2-py3.10.egg
decorator 4.4.2 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/decorator-4.4.2-py3.10.egg
Searching for PyYAML==5.4.1
Best match: PyYAML 5.4.1
Adding PyYAML 5.4.1 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for yacs==0.1.8
Best match: yacs 0.1.8
Processing yacs-0.1.8-py3.10.egg
yacs 0.1.8 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/yacs-0.1.8-py3.10.egg
Searching for pyparsing==2.4.7
Best match: pyparsing 2.4.7
Adding pyparsing 2.4.7 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for Jinja2==3.0.3
Best match: Jinja2 3.0.3
Adding Jinja2 3.0.3 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for googledrivedownloader==0.4
Best match: googledrivedownloader 0.4
Processing googledrivedownloader-0.4-py3.10.egg
googledrivedownloader 0.4 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/googledrivedownloader-0.4-py3.10.egg
Searching for rdflib==6.1.1
Best match: rdflib 6.1.1
Processing rdflib-6.1.1-py3.10.egg
rdflib 6.1.1 is already the active version in easy-install.pth
Installing csv2rdf script to /usr/bin
Installing rdf2dot script to /usr/bin
Installing rdfgraphisomorphism script to /usr/bin
Installing rdfpipe script to /usr/bin
Installing rdfs2dot script to /usr/bin

Using /usr/lib/python3.10/site-packages/rdflib-6.1.1-py3.10.egg
Searching for requests==2.26.0
Best match: requests 2.26.0
Adding requests 2.26.0 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for scikit-learn==1.0.2
Best match: scikit-learn 1.0.2
Processing scikit_learn-1.0.2-py3.10-linux-x86_64.egg
scikit-learn 1.0.2 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/scikit_learn-1.0.2-py3.10-linux-x86_64.egg
Searching for networkx==2.6.3
Best match: networkx 2.6.3
Processing networkx-2.6.3-py3.10.egg
networkx 2.6.3 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/networkx-2.6.3-py3.10.egg
Searching for pytz==2021.3
Best match: pytz 2021.3
Adding pytz 2021.3 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for python-dateutil==2.8.2
Best match: python-dateutil 2.8.2
Adding python-dateutil 2.8.2 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for typing-extensions==4.0.1
Best match: typing-extensions 4.0.1
Adding typing-extensions 4.0.1 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for MarkupSafe==2.0.1
Best match: MarkupSafe 2.0.1
Adding MarkupSafe 2.0.1 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for setuptools==57.4.0
Best match: setuptools 57.4.0
Adding setuptools 57.4.0 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for isodate==0.6.1
Best match: isodate 0.6.1
Processing isodate-0.6.1-py3.10.egg
isodate 0.6.1 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/isodate-0.6.1-py3.10.egg
Searching for urllib3==1.26.7
Best match: urllib3 1.26.7
Adding urllib3 1.26.7 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for idna==3.3
Best match: idna 3.3
Adding idna 3.3 to easy-install.pth file

Using /usr/lib/python3.10/site-packages
Searching for chardet==4.0.0
Best match: chardet 4.0.0
Adding chardet 4.0.0 to easy-install.pth file
Installing chardetect script to /usr/bin

Using /usr/lib/python3.10/site-packages
Searching for threadpoolctl==3.1.0
Best match: threadpoolctl 3.1.0
Processing threadpoolctl-3.1.0-py3.10.egg
threadpoolctl 3.1.0 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/threadpoolctl-3.1.0-py3.10.egg
Searching for joblib==1.1.0
Best match: joblib 1.1.0
Processing joblib-1.1.0-py3.10.egg
joblib 1.1.0 is already the active version in easy-install.pth

Using /usr/lib/python3.10/site-packages/joblib-1.1.0-py3.10.egg
Finished processing dependencies for torch-geometric-temporal==0.51.0
```
#### cd examples

```
[max@workstation pytorch_geometric_temporal]$ ls
build  CONTRIBUTING.md  dataset  dist  docs  examples  LICENSE  notebooks  README.md  readthedocs.yml  setup.py  test  torch_geometric_temporal  torch_geometric_temporal.egg-info
[max@workstation pytorch_geometric_temporal]$ cd examples/
[max@workstation examples]$ ls
recurrent
[max@workstation examples]$ cd recurrent/
[max@workstation recurrent]$ ls
a3tgcn2_example.py  agcrn_example.py  dygrencoder_example.py  evolvegcno_example.py  gconvgru_example.py   lightning_example.py  mpnnlstm_example.py
a3tgcn_example.py   dcrnn_example.py  evolvegcnh_example.py   gclstm_example.py      gconvlstm_example.py  lrgcn_example.py      tgcn_example.py
```

#### Running an example

```
[max@workstation recurrent]$ python tgcn_example.py 
Traceback (most recent call last):
  File "/home/max/Projects/pytorch_geometric_temporal/examples/recurrent/tgcn_example.py", line 5, in <module>
    from torch_geometric_temporal.nn.recurrent import TGCN
ModuleNotFoundError: No module named 'torch_geometric_temporal.nn.recurrent'
[max@workstation recurrent]$ ls
a3tgcn2_example.py  agcrn_example.py  dygrencoder_example.py  evolvegcno_example.py  gconvgru_example.py   lightning_example.py  mpnnlstm_example.py
a3tgcn_example.py   dcrnn_example.py  evolvegcnh_example.py   gclstm_example.py      gconvlstm_example.py  lrgcn_example.py      tgcn_example.py
[max@workstation recurrent]$ python tgcn_example.py 
Traceback (most recent call last):
  File "/home/max/Projects/pytorch_geometric_temporal/examples/recurrent/tgcn_example.py", line 5, in <module>
    from torch_geometric_temporal.nn.recurrent import TGCN
ModuleNotFoundError: No module named 'torch_geometric_temporal.nn.recurrent'
```

**Comment by benedekrozemberczki** [comment]
Hi there, I would recommend installing Pytorch Geometric and Scatter beforehand. After that I would suggest using pip. @BaseMax could you star the repo?
