### ISSUE TITLE
How to distribute the model to compute in multiple GPUs?

### ISSUE THREAD

**Issue by Adricu8** [benedekrozemberczki/pytorch_geometric_temporal#156]
I am trying to distribute the model computation in multiple GPUs using [DataParallel](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#module-torch_geometric.nn.data_parallel) from Pytorch Geometric library
I was trying to follow this [example](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/multi_gpu/data_parallel.py)  but I am running into errors. 
Is this the way to do it or should I look somewhere else?
Are there any examples out there to distribute models from Pytorch Geometric Temporal library?

**Comment by SherylHYX** [comment]
Could you show your example explicitly and what error messages you got? Perhaps have a look at this [tutorial](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html)?

**Comment by SherylHYX** [comment]
The issue seems to be that you are not putting your data and model on both GPU and CPU: "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" Could you try putting your data object on GPU also?

**Comment by SherylHYX** [comment]
In the model definition, when doing calculation, you could map the data objects to the same device by e.g. "X = X.to(Y)"

**Comment by Adricu8** [comment]
I am still running into errors regarding this. It seems that the previous error was caused by sending a custom object to the model, instead of tensors. This is not supported by DataParallel as only the tensors can be split into their batch dimension.

Now then, after solving the previous error, there is another error triggered by pytorch geometric:

> Exception has occurred: IndexError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
Caught IndexError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/raid0/users/acg384/workspace/code/LSTM_ddp2.py", line 49, in forward
    h_0 = self.recurrent1(x, edge_index, edge_weight)
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch_geometric_temporal/nn/recurrent/gconv_gru.py", line 163, in forward
    Z = self._calculate_update_gate(X, edge_index, edge_weight, H)
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch_geometric_temporal/nn/recurrent/gconv_gru.py", line 120, in _calculate_update_gate
    Z = self.conv_x_z(X, edge_index, edge_weight)
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch_geometric/nn/conv/cheb_conv.py", line 143, in forward
    edge_index, norm = self.__norm__(edge_index, x.size(self.node_dim),
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch_geometric/nn/conv/cheb_conv.py", line 110, in __norm__
    edge_index, edge_weight = remove_self_loops(edge_index, edge_weight)
  File "/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch_geometric/utils/loop.py", line 36, in remove_self_loops
    mask = edge_index[0] != edge_index[1]
IndexError: index 1 is out of bounds for dimension 0 with size 1
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/_utils.py]()", line 434, in reraise
    raise exception
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py]()", line 86, in parallel_apply
    output.reraise()
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py]()", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py]()", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/site-packages/torch/nn/modules/module.py]()", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[/mnt/raid0/users/acg384/workspace/code/LSTM_ddp2.py]()", line 176, in <module>
    y_hat = model(x, edge_index, edge_weight)
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/runpy.py]()", line 87, in _run_code
    exec(code, run_globals)
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/runpy.py]()", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/runpy.py]()", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/runpy.py]()", line 87, in _run_code
    exec(code, run_globals)
  File "[/home/acg384/miniconda3/envs/pytorch_test/lib/python3.9/runpy.py]()", line 197, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,

Any idea what is causing this?
Thank you!
