### ISSUE TITLE
DCRNN METRLADatasetLoader example tensor dimension errors

### ISSUE THREAD

**Issue by jwsmithers** [benedekrozemberczki/pytorch_geometric_temporal#54]
Hi there, 

Thanks for the great library!
I'm trying to reproduce an example found on the introduction page of the docs using the METRLADatasetLoader. My code is below:

```python
from tqdm import tqdm
import torch
import torch.nn.functional as F
from torch_geometric_temporal.nn.recurrent import DCRNN
import torch_geometric_temporal
from torch_geometric_temporal.dataset import METRLADatasetLoader
from torch_geometric_temporal.signal import temporal_signal_split


loader = METRLADatasetLoader()

dataset = loader.get_dataset()

train_dataset, test_dataset = temporal_signal_split(dataset, train_ratio=0.5)

class RecurrentGCN(torch.nn.Module):
    def __init__(self, node_features):
        super(RecurrentGCN, self).__init__()
        self.recurrent = DCRNN(node_features, 32, 1)
        self.linear = torch.nn.Linear(32, 1)

    def forward(self, x, edge_index, edge_weight):
        h = self.recurrent(x, edge_index, edge_weight)
        h = F.relu(h)
        h = self.linear(h)
        return h

model = RecurrentGCN(node_features = 4)

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

model.train()

for epoch in tqdm(range(200)):
    cost = 0
    for time, snapshot in enumerate(train_dataset):
        print(snapshot.x.shape, snapshot.edge_index.shape, snapshot.edge_attr.shape)
        y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
        cost = cost + torch.mean((y_hat-snapshot.y)**2)
    cost = cost / (time+1)
    cost.backward()
    optimizer.step()
    optimizer.zero_grad()
```

That fails with:

```shell
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    y_hat = model(snapshot.x, snapshot.edge_index, snapshot.edge_attr)
  File "/private/tmp/test/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "test.py", line 23, in forward
    h = self.recurrent(x, edge_index, edge_weight)
  File "/private/tmp/test/env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/private/tmp/test/env/lib/python3.7/site-packages/torch_geometric_temporal/nn/recurrent/dcrnn.py", line 181, in forward
    Z = self._calculate_update_gate(X, edge_index, edge_weight, H)
  File "/private/tmp/test/env/lib/python3.7/site-packages/torch_geometric_temporal/nn/recurrent/dcrnn.py", line 144, in _calculate_update_gate
    Z = torch.cat([X,H], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 3 and 2
```
Package versions:
```shell
torch==1.8.0
torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html
torch-geometric==1.7.0
torch-geometric-temporal==0.27
```

Am I doing something stupid?
Thanks in advance!

**Comment by benedekrozemberczki** [comment]
The MetrLA dataset returns snapshots of features that were not designed for DCRNN exactly. There is an extra dimension on which you would have to iterate. If you print it you can see that the shape is not compatible with the DCRNN weights.

**Comment by SherylHYX** [comment]
> The MetrLA dataset returns snapshots of features that were not designed for DCRNN exactly. There is an extra dimension on which you would have to iterate. If you print it you can see that the shape is not compatible with the DCRNN weights.

Yeah, this is also true for MTGNN and GMAN models for example.

**Comment by smkaropp** [comment]
Thanks for the great library. I was wondering which model exactly from package would you recommend to use on MetrLA dataset.
